spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: service-users
            uri: lb://service-users
            predicates:
              - Path=/user/**, /swagger-users/**, /v3/api-docs/**
            filters:
              - RewritePath=/swagger-users(?<segment>.*), /swagger-ui${segment}
          - id: service-login
            uri: lb://service-login
            predicates:
              - Path=/login/**
          - id: service-imc
            uri: lb://service-imc
            predicates:
              - Path=/imc/**
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      preferIpAddress: true
