spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: service-users
            uri: lb://service-users
            predicates:
              - Path=/user/**
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      preferIpAddress: true
