spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: service-users
            uri: lb://service-users
            predicates:
              - Path=/user/**, /docs-users/**, /v3/api-docs/users/**
            filters:
              - RewritePath=/docs-users(?<segment>.*), /swagger-ui${segment}
          - id: service-login
            uri: lb://service-login
            predicates:
              - Path=/login/**, /docs-login/**, /v3/api-docs/login/**
            filters:
              - RewritePath=/docs-login(?<segment>.*), /swagger-ui${segment}
          - id: service-imc
            uri: lb://service-imc
            predicates:
              - Path=/imc/**, /docs-imc/**, /v3/api-docs/imc/**
            filters:
               - RewritePath=/docs-imc(?<segment>.*), /swagger-ui${segment}
server:
  port: 8765
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      preferIpAddress: true
