spring:
  application:
    name: service-imc
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
      preferIpAddress: true
springdoc:
  api-docs:
    path: /v3/api-docs/imc
env-variables:
  jwtSecret: ${JWT_SECRET:$LXbs2WhnF#S&NJJ^aCo#h$ASFL2P7qNFb$D$Mf&W2xz5hC7c7}