spring:
  application:
    name: service-users
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_users
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
      preferIpAddress: true
springdoc:
  api-docs:
    path: /v3/api-docs/users